theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
title:
  SDL2 C Tutorials, Examples, Demos and more
description:
  Comprehensive Collection of SDL2 and OpenGL C-Code.
  Procedural Sounds and Graphics, plus GLSL Shaders for Game-Programming and general purpose.
