# Developer's Note: This is a sample _config.yml file offered with
# jekyll-theme-prologue for your convenience. To use it, move it to your
# project's root directory. Please note that the following lines are
# NECESSARY for Prologue to work correctly:
#
# theme: jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:
  Acry's Coding Site


#title: Acry's Coding Site
subtitle:
  Talk is cheap... show me the Code!

description:
  SDL2, Python3, C, GTK3 Tutorials. My Portfolio.

author: Carsten Holtkamp
email: Carsten-Holtkamp@T-Online.de
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
#baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "http://acry.github.io" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: "https://www.linkedin.com/in/carsten-holtkamp-5b4405a5/"
github_url: "https://github.com/Acry"
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
#theme: jekyll-theme-prologue
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]

plugins:
  - jekyll-seo-tag
